### ISSUE TITLE
Suggest an example with PROGMEM zone structures

### ISSUE THREAD

**Issue by nsayer** [JChristensen/Timezone#1]
If you're going to configure a clock with a large collection of zone rules from which you will pick a single to be the active set, then you're going to want an array of zone data in flash rather than in RAM.

You might consider adding and/or altering one of the examples to illustrate that.

**Comment by JChristensen** [comment]
I never got back to this so I'm closing it. If you care to contribute a complete example using PROGMEM, I could include that in the examples folder. Regarding setRules(), that will be included in an upcoming commit.
