### ISSUE TITLE
DST flag is on on same rules timezone

### ISSUE THREAD

**Issue by azevedo-manuel** [JChristensen/Timezone#12]
Hello
I've tested a few times and it looks that when there's no DST for a given time zone (rules for start and end are the same, as per documentation) , when checking for locIsDST(localTime) returns TRUE.
Is this expected?

**Comment by JChristensen** [comment]
Hmmm, no, not expected! Now that I look at it I'm not surprised though, probably not a condition I'd considered. Thanks for the catch, I'll have a closer look, hopefully there is a simple fix.
