### ISSUE TITLE
Using this lib to set RTC to UTC

### ISSUE THREAD

**Issue by scls19fr** [JChristensen/Timezone#16]
Hello,

I own an Adafruit Data Logger Shield https://www.adafruit.com/product/1141

I followed this tutorial https://learn.adafruit.com/adafruit-data-logger-shield/using-the-real-time-clock

This part of code

    if (! rtc.initialized()) {
      Serial.println("RTC is NOT running!");
      // following line sets the RTC to the date & time this sketch was compiled
      rtc.adjust(DateTime(F(__DATE__), F(__TIME__)));

adjust RTC to computer date/time... but it's using computer local date/time.

I'm looking for a way to adjust RTC using UTC when programming Arduino.

Similar question on SO https://arduino.stackexchange.com/questions/38581/setting-time-to-utc-with-data-logger-shield-with-rtc-ds1387

I wonder how this library could help to achieve this task.

Kind regards

**Comment by JChristensen** [comment]
Please raise issues here only for actual problems with the library, not for problems with your code. Please use the Arduino forum or similar site for help with your code.
