### ISSUE TITLE
WorldClock Example, Compile Error

### ISSUE THREAD

**Issue by alezarate** [JChristensen/Timezone#20]
I Try to run the example in Arduino 1.8.3 but appear the follow error:

WorldClock:41: error: 'dowSunday' was not declared in this scope

 TimeChangeRule usCDT = {"CDT", Second, dowSunday, Mar, 2, -300};

...

any idea?

**Comment by WilkoV** [comment]
I had the same problem. Change #include <Time.h> to #include <TimeLib.h>. This issue should be linked to https://github.com/JChristensen/Timezone/issues/7

**Comment by alezarate** [comment]
Thank You!
