### ISSUE TITLE
Possibility of adding a specific day of the month rule

### ISSUE THREAD

**Issue by azevedo-manuel** [JChristensen/Timezone#21]
Would it be possible to have rules that instead of DOW, change on a specific day/month pair?
I heard about this requirement, but according to Wikipedia, Sweden used it in the past, but only Iran uses this kind of DST today.

**Comment by azevedo-manuel** [comment]
I added a dirty hack to support fixed dates
If adding __tzFixedRuleOffset__+__dayOfMonth__ instead of __dweek__ (which accepts values from 1 to 7), it will identify the rule as a fixed date rule.

It's not a clean implementation, but won't break existing **libTimeZone** implementations

https://github.com/azevedo-manuel/Timezone/commit/92b493f236c8cae8c98358e60372e727691d92eb
So far seems to be working correctly!

**Comment by JChristensen** [comment]
Outside the scope of this library.

**Comment by doanerock** [comment]
This is a shame that Timezone can not handle all time zones even thought people are willing to pitch in to help add the functionality.

**Comment by JChristensen** [comment]
Yes indeed. Maybe someone else will step up to create and maintain a [tz database](https://en.wikipedia.org/wiki/Tz_database) for the Arduino world. I am [unable](https://gist.github.com/JChristensen/f390dea4b1f713b245918500ac45cc31).
