### ISSUE TITLE
Very big numbers does not work

### ISSUE THREAD

**Issue by bobybobybob** [JChristensen/Timezone#23]
I try to create a Daysafingtime yes or no

my idea is i enter crazy numbers and make than a if Year is = Year => no Daysafingtime, else yes Daysafingtime

but 

TimeChangeRule myDST = {"EDT", Second, Sun, Mar, 2, -198201600};    //Daylight time = UTC - litte more than a year
TimeChangeRule mySTD = {"EST", First, Sun, Nov, 2, -300};     //Standard time = UTC - 5 hours
Timezone myTZ(myDST, mySTD);

are ignored. look like a bug.

**Comment by JChristensen** [comment]
There's no reason that they should. The offset field is a 16-bit integer, so it's range is only -32,768 to 32,767. But practically speaking, since the offset is minutes difference from UTC, there's no practical reason for it to have an absolute value greater than 1440 (24*60).
