### ISSUE TITLE
Support more than two transitions during a year

### ISSUE THREAD

**Issue by me21** [JChristensen/Timezone#25]
There's Africa/Casablanca, which is currently running with **four** transitions per year, doing two cycles in and out of DST each year, using "summer" time in spring and autumn, "winter" time in summer and winter.

See https://www.timeanddate.com/time/zone/morocco/casablanca

**Comment by JChristensen** [comment]
Sorry, I am unable to address this. Suggest forking the library or otherwise doing your own thing.

**Comment by me21** [comment]
Would you accept a pull request if it's done?

**Comment by JChristensen** [comment]
Only if I had time to review and test, which won't be anytime soon.
