### ISSUE TITLE
Sometimes the date and time are incorrect

### ISSUE THREAD

**Issue by yonaguska** [JChristensen/Timezone#26]
I've used your code in a Weather Node project because my code didn't handle daylight savings time. But I sometimes see the time and date are incorrect. It's not consistent and I can't see a pattern to it, yet. For instance, I just restarted my node and I see the error. My local date and time is Nov. 12, 2017 11:41 AM CST, and your code is showing Nov. 12, 2017 00:55:47 CST. My node is showing Nov. 12, 2017 00:39:10 CST, but that might be a code bug on my part. My primary concern is the discrepancy between the actual time and what your code is returning. Have you seen this happen? 

I've included a screenshot showing the discrepancies.

Thanks,
-Kirk

![2017-11-12 11 41 58 -0600 time issues](https://user-images.githubusercontent.com/15708964/32701694-c438e964-c79f-11e7-8671-3f977c725612.png)

**Comment by JChristensen** [comment]
I have not seen this nor am I aware of any similar reports. Do the example sketches also exhibit the same issue? If you can produce the issue consistently, please submit a [SSCCE.](http://www.sscce.org/) I cannot debug your code and please do not assume that I have identical hardware.
