### ISSUE TITLE
symlink CONTRIBUTING.md breaks checkout under Linux

### ISSUE THREAD

**Issue by borisneubert** [JChristensen/Timezone#27]
git clone produces the error:

`error: unable to create symlink CONTRIBUTING.md: Input/Output Error`

with git version 2.14.1 under Linux on a filesystem that supports symlinks.

Please see  [here](https://stackoverflow.com/questions/18411200/git-unable-to-create-symlink-file-name-too-long) or a potential fix

**Comment by JChristensen** [comment]
That's interesting because while I did play with a symlink for that file, it was not a symlink at the time of the commit and is not currently on my system.

**Comment by borisneubert** [comment]
![grafik](https://user-images.githubusercontent.com/8795819/34908138-5c6f9db0-f88b-11e7-88c9-89c31eb54a70.png)

The symbol in the GitHub UI suggests that it is a symlink. Above mentioned link makes me think that the issue is hard to detect and resolve.

**Comment by JChristensen** [comment]
Yes I did notice that. I removed the file, committed, then added it back and committed again.
Please let me know if that fixes it.

**Comment by borisneubert** [comment]
Now it works fine for me. Thank you!

**Comment by JChristensen** [comment]
Great, thank you for the catch!
Fixed by 3057e97e1eeb4f00357db7800fa432edd188a0d8
