### ISSUE TITLE
Compatible with Teensy 3.2?

### ISSUE THREAD

**Issue by lancehornby** [JChristensen/Timezone#32]
I currently have a DS1307 RTC connected to my Teensy 3.2 and I was wondering if there are any changes that need to be made to the library for it to work?

Thanks in advance!

**Comment by JChristensen** [comment]
Hello, I don't have a Teensy and I don't remember any reports one way or the other. But the library is fairly straightforward, I imagine it would work; best to just give it a try. I'd be interested to hear how it goes!
