### ISSUE TITLE
user configurable timezone

### ISSUE THREAD

**Issue by avarachanvc** [JChristensen/Timezone#4]
How can I use the clock example and set the timezone based on a user timezone ? and access it from other functions. Or simply, how can I change the timezone from inside a function after it is initialized?

eg:
//US Eastern Time Zone (New York, Detroit)
TimeChangeRule usEDT = {"EDT", Second, Sun, Mar, 2, -240};  //Eastern Daylight Time = UTC - 4 hours
TimeChangeRule usEST = {"EST", First, Sun, Nov, 2, -300};   //Eastern Standard Time = UTC - 5 hours
Timezone myTZ(usEDT, usEST);

Now, how can I change this to myTZ(usMDT,usMST)?

**Comment by JChristensen** [comment]
Please raise issues here only if there is a demonstrable problem with the library; this is not the place to design or debug your code. Suggest posting on the Arduino forum instead. However, [here](http://adventuresinarduinoland.blogspot.com/2013/04/how-long-was-power-out.html) is a project with user-configurable time zone that may be instructive.
