### ISSUE TITLE
question: TimeChangeRule variable types

### ISSUE THREAD

**Issue by remcoNL** [JChristensen/Timezone#42]
Hi Jack,

Thanks so much for your lib, it's really good. 

I am trying to convert a String from user input to this:

`TimeChangeRule myRule = {abbrev, week, dow, month, hour, offset};`

Can you please tell me the type of variables that are needed?

**Comment by JChristensen** [comment]
Does this help?
https://github.com/JChristensen/Timezone/blob/master/src/Timezone.h#L25

**Comment by remcoNL** [comment]
It does! Thanks

**Comment by JChristensen** [comment]
You're welcome!
