### ISSUE TITLE
Bug in several examples (the library itself is not affected).

### ISSUE THREAD

**Issue by yunjova** [JChristensen/Timezone#48]
In de function `time_t compileTime()` the array to hold the month string is an entry too short.
    `char chMon[3], *m;` has size 3 entries.
   ` chMon[3] = '\0';` assigns te 4th entry - out-of-bounds.

See: chMon in Clock.ino, WorldClock.ino and `compMon` in Change_TZ_1.ino, Change_TZ_2.ino.

Kind regards.

**Comment by JChristensen** [comment]
Yikes! I can't believe I did that. Thanks for letting me know.
