### ISSUE TITLE
AVR vs SAMD Architecture

### ISSUE THREAD

**Issue by flyusa1** [JChristensen/Timezone#53]
I am using Adafruit's ItsyBitsy M4 SAMD board with your Timezone library for a new project and I am getting this error message on compilation.

"WARNING: library Timezone claims to run on avr architecture(s) and may be incompatible with your current board which runs on samd architecture(s)."

Is there a work around you can advise? I really like to use your library for a project on the new board; the library has been working perfectly on the Uno and the ProTrinket boards. 

Please let me know. Thank you, 

Kind Regards.

**Comment by JChristensen** [comment]
Greetings,
In the library.properties file, [change this line](https://github.com/JChristensen/Timezone/blob/7cf1425b4ee598573e85b6fa124d4514f71c2586/library.properties#L9) to read:
```c++
architectures=*
```
