### ISSUE TITLE
DST issue?

### ISSUE THREAD

**Issue by JoaquimBoavida** [JChristensen/Timezone#56]
First, thanks to Jack for the excelent work!
I don't know if what i'm going to describe is an issue or not, but here it goes:

I have 3 LED clocks on my network and they work just fine (all of them). I'm in the Lisbon/GMT timezone and everything works just fine including DST calculation.

However, in case of a power cut , whe the 3 clocks are turned on at exact same time, some of them (randomly) don't calcutate the DST. I got the standard GMT time.
I beleive that the issue is related that all 3 clocks sync at almost same time, and the request came from the same public IP...

What puzzles me, is that i got the correct time (mens that sync worked in all 3 clocks)... So why I go the wrong DST? 

If i cycle power the "wrong" clock everything syncs ok again. If I turn the clocks one by one is also ok everytime.    

Thanks again for the excelent and sorry for the trouble
Joaquim from Portugal

**Comment by JChristensen** [comment]
Hello Joaquim,
Nice to hear from Portugal!
Intermittent problems like this can be hard to troubleshoot. I have not heard of similar issues with the library. I'm not sure what steps you may have taken to debug the problem, but I might put in some print statements to help find the problem. If you do decide there is an actual problem with the library, we can re-open this issue. In that case, if you can provide [a short example](http://www.sscce.org/) that demonstrates the problem, that would help me a lot.
Good luck and best regards ... Jack
