### ISSUE TITLE
ESP32 warning

### ISSUE THREAD

**Issue by guybuys** [JChristensen/Timezone#60]
I used this library on an ESP32 board. As far as I can see, the library works as expected, however, I have got a warning during compilation:

WARNING: Timezone library claims to run under architecture avr and may be incompatible with your current board running under architecture esp32.

I understood the author is writing code exclusive for AVR architecture so this might not be accepted as an issue but because ESP has integrated Wifi and it is very easy to request time with NTP Client, this library is very interesting for DST.

**Comment by JChristensen** [comment]
Correct, please see #34.
