### ISSUE TITLE
How about using the standard POSIX ENV time definition string

### ISSUE THREAD

**Issue by MikeyMoMo** [JChristensen/Timezone#61]
Instead of reinventing the whole thing, I would suggest that you should be using the standard IBM/POSIX ENV time string.  Their format is like this:

```
HAST10HADT,M4.2.0/03:0:0,M10.2.0/03:0:00
AST9ADT,M3.2.0,M11.1.0
AST9ADT,M3.2.0/03:0:0,M11.1.0/03:0:0
EST5EDT,M3.2.0/02:00:00,M11.1.0/02:00:00
GRNLNDST3GRNLNDDT,M10.3.0/00:00:00,M2.4.0/00:00:00
EST5EDT,M3.2.0/02:00:00,M11.1.0
EST5EDT,M3.2.0,M11.1.0/02:00:00
CST6CDT,M3.2.0/2:00:00,M11.1.0/2:00:00
MST7MDT,M3.2.0/2:00:00,M11.1.0/2:00:00
PST8PDT,M3.2.0/2:00:00,M11.1.0/2:00:00
```

They are well known and standard.  There are about 680 of them to cover all known, well defined time zones and DST parameters.  Your method discards this and creates a new version that the user has to create while with the standard way, the information is already created.   All you need to do it parse it out.  All you need is there.

Just a suggestion.  Surely would make your code easier to use.

Mike

**Comment by JChristensen** [comment]
@MikeyMoMo,

Thanks for the suggestion. If you are aware of the official definition of the POSIX format, please provide a link. I found [this](https://developer.ibm.com/articles/au-aix-posix/) and [this](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html) but am not sure that either is a definitive or complete specification.

Having said that, it seems like parsing the POSIX format completely and correctly would be fairly complicated.

Regards ...jc
