### ISSUE TITLE
Error in hour character  display

### ISSUE THREAD

**Issue by codeput** [JChristensen/Timezone#67]
Hi, I managed to program my ESP correctly, but the time string appears like this "08:18:33.045 -> ============    17 55  Saturday ---- 13 4 2024" in practice the hours are not visible and I think that for this reason everything doesn't work.

**Comment by JChristensen** [comment]
I cannot respond if I cannot duplicate the issue. If you would provide a [SSCCE](http://www.sscce.org/), that would help greatly.

**Comment by codeput** [comment]
Hi, thanks for the quick reply, I solved it by adding an empty character on the string "SERIALPORT.println(String(" ") + hour(local) + String(" ") + minute(local) + String(" ") + second (local) + String(" ") + String(weekdays[weekday(local)-1]) + String(" ---- ") + day(local) + String(" ") + month(local) + String (" ") + year(local));"
Thanks again.

**Comment by codeput** [comment]
Hi, thanks for the quick reply, I solved it by adding an empty character on the string "SERIALPORT.println(String(" ") + hour(local) + String(" ") + minute(local) + String(" ") + second (local) + String(" ") + String(weekdays[weekday(local)-1]) + String(" ---- ") + day(local) + String(" ") + month(local) + String (" ") + year(local));"
Thanks again.

**Comment by JChristensen** [comment]
Hi, thanks for the update. Glad you found your issue.
